<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>NzbDrone.Plugin.MusiKat</RootNamespace>
    <AssemblyName>Lidarr.Plugin.MusiKat</AssemblyName>
    <AssemblyVersion>0.1.3.0</AssemblyVersion>
    <FileVersion>0.1.3.0</FileVersion>
    <InformationalVersion>0.1.3</InformationalVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lidarr\src\NzbDrone.Core\Lidarr.Core.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
    <ProjectReference Include="..\Lidarr\src\NzbDrone.Common\Lidarr.Common.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>
</Project>
